### ISSUE TITLE
simple_af_network.ipynb line In [141]:

### ISSUE THREAD

**Issue by shashankrustagi** [llSourcell/neural_networks#6]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-4e0bb9a42bbd> in <module>()
----> 1 for j in xrange(6000):
      2 
      3 # Forward propagate through layers 0, 1, and 2
      4     layer0 = input_data
      5     layer1 = activate(np.dot(layer0,synaptic_weight_0))

NameError: name 'xrange' is not defined

**Comment by lluflliks** [comment]
Don't use xrange, use range instead

**Comment by shashankrustagi** [comment]
thanks @lluflliks  😎
