### ISSUE TITLE
please resolve

### ISSUE THREAD

**Issue by shashankrustagi** [llSourcell/neural_networks#7]
print(activate(np.dot(array([0, 1, 1]), syn0)))
​
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-26-0597e43eebd0> in <module>()
----> 1 print(activate(np.dot(array([0, 1, 1]), syn0)))

NameError: name 'array' is not defined

**Comment by lluflliks** [comment]
I resolved this already...first issue
"In the simple_AF NN
Code says
print(activate(np.dot(array([0, 1, 1, 0]), syn0)))

Should be

print(activate(np.dot([0, 1, 1], synaptic_weight_0)))

Incorrect variable name."

**Comment by antmarakis** [comment]
Maybe it was meant to be `np.array`?
